plugins {
    id 'project-conventions'
}

dependencies {
    implementation 'org.springframework.retry:spring-retry'
    implementation 'org.springframework:spring-aspects'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    
    // Rate Limiting Dependencies
    implementation 'com.github.vladimir-bukhtoyarov:bucket4j-core:7.6.0'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

springBoot {
    mainClass = 'com.reliaquest.api.ApiApplication'
}